# Generated by Django 6.0.4 on 2026-04-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_circumferences', models.JSONField(blank=True, null=True)),
                ('skinfolds', models.JSONField(blank=True, null=True)),
                ('limitations', models.TextField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('answers_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questionnaire_responses', to='accounts.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('photo_type', models.CharField(max_length=50)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress_photos', to='accounts.coachprofile')),
                ('questionnaire_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='checks.questionnaireresponse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('questionnaire_type', models.CharField(max_length=50)),
                ('frequency_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('objective', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_templates', to='accounts.coachprofile')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='questionnaire_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checks.questionnairetemplate'),
        ),
    ]
