# Generated by Django 6.0.4 on 2026-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
