# Generated by Django 6.0.4 on 2026-04-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAnamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis_date', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('intolerances', models.TextField(blank=True, null=True)),
                ('lifestyle_notes', models.TextField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=100, null=True)),
                ('food_habits', models.TextField(blank=True, null=True)),
                ('weight_history', models.TextField(blank=True, null=True)),
                ('path_goal', models.TextField(blank=True, null=True)),
                ('professional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_anamnesis', to='accounts.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('relationship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_relationships_as_client', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_relationships_as_coach', to='accounts.coachprofile')),
            ],
        ),
    ]
