# Generated by Django 6.0.4 on 2026-04-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrition_goal', models.CharField(blank=True, max_length=200, null=True)),
                ('daily_kcal', models.IntegerField(blank=True, null=True)),
                ('protein_target_g', models.IntegerField(blank=True, null=True)),
                ('carb_target_g', models.IntegerField(blank=True, null=True)),
                ('fat_target_g', models.IntegerField(blank=True, null=True)),
                ('meals_per_day', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='accounts.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_assignments', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_assignments_given', to='accounts.coachprofile')),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nutrition.nutritionplan')),
            ],
        ),
    ]
