# Generated by Django 6.0.4 on 2026-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='professional_type',
            field=models.CharField(choices=[('COACH', 'Coach (Allenamento + Nutrizione)'), ('ALLENATORE', 'Allenatore'), ('NUTRIZIONISTA', 'Nutrizionista')], default='COACH', max_length=20),
        ),
    ]
