# Generated by Django 6.0.4 on 2026-04-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('target_muscles', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_muscles', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('movement_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_type', models.CharField(blank=True, max_length=50, null=True)),
                ('alternative_exercises_notes', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_order', models.IntegerField()),
                ('day_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('focus_area', models.CharField(blank=True, max_length=200, null=True)),
                ('day_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='accounts.clientprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments_given', to='accounts.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('set_count', models.IntegerField(blank=True, null=True)),
                ('rep_count', models.IntegerField(blank=True, null=True)),
                ('rep_range', models.CharField(blank=True, max_length=50, null=True)),
                ('rir', models.IntegerField(blank=True, null=True)),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('rm_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('load_percentage', models.IntegerField(blank=True, null=True)),
                ('recovery_seconds', models.IntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, max_length=50, null=True)),
                ('execution_type', models.CharField(blank=True, max_length=100, null=True)),
                ('technique_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('completion_status', models.CharField(max_length=50)),
                ('perceived_difficulty', models.IntegerField(blank=True, null=True)),
                ('total_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='accounts.clientprofile')),
                ('workout_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workoutassignment')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('goal', models.CharField(blank=True, max_length=200, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='accounts.coachprofile')),
            ],
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.workoutplan'),
        ),
    ]
